### ISSUE TITLE
Replace synchronous XHR with async request

### ISSUE THREAD

**Issue by stephenlacy** [efexen/elixir-tab#2]
https://github.com/efexen/elixir-tab/blob/master/elixir_tab.js#L7
Synchronous XHR requests are deprecated and block the main thread when loading.
I am suggesting replacing it with a callback pattern. I can send a PR if you would like.

**Comment by efexen** [comment]
I completely agree. I had planned on replacing them with a fetch tomorrow when I have a bit of time but happy for you to put together a PR instead 👍
